<?php

namespace WorldBundle\Repository;

/**
 * BeachRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeachRepository extends \Doctrine\ORM\EntityRepository
{
}
