<?php

namespace WorldBundle\Repository;

/**
 * BottleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BottleRepository extends \Doctrine\ORM\EntityRepository
{
}
