<?php

namespace WorldBundle\Repository;

/**
 * ForestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForestRepository extends \Doctrine\ORM\EntityRepository
{
}
