<?php

namespace WorldBundle\Repository;

/**
 * HutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HutRepository extends \Doctrine\ORM\EntityRepository
{
}
