<?php

namespace WorldBundle\Repository;

/**
 * IslandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IslandRepository extends \Doctrine\ORM\EntityRepository
{
}
