<?php

namespace WorldBundle\Repository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAllItem(){
		return $this
            ->createQueryBuilder('i')
            ->where('i.name <> :name')
            ->setParameter('name', "bottle")
            ->getQuery()
        ;
	}
}
