<?php

namespace WorldBundle\Repository;

/**
 * UsableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsableRepository extends \Doctrine\ORM\EntityRepository
{
}
