<?php

namespace WorldBundle\Repository;

/**
 * WorldGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorldGameRepository extends \Doctrine\ORM\EntityRepository
{
}
